# docker-compose.yml
version: '3.8'

services:
  client:
    build: ./client-om
    ports:
      - '3000:3000'
    environment:
      NEXT_PUBLIC_GRAPHQL_URL: http://server:4000
      NEXT_PUBLIC_GRAPHQL_PATH: /graphql
    depends_on:
      - server

  server:
    build: ./server-om
    ports:
      - '4000:4000'
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      DATABASE_URL: postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}
    depends_on:
      - db

  db:
    image: postgres:13
    container_name: om-accountants-pg
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - '5432:5432'
    volumes:
      - db-data:/var/lib/postgresql/data

volumes:
  db-data:
